name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # HTTP requests to your Flask backend
  http: ^1.6.0

  # Directory utilities (you *can* use this later if needed)
  path_provider: ^2.1.2

  # Request storage permission on Android
  permission_handler: ^11.3.1

  # Save CSV files to disk
  file_saver: ^0.2.14

  url_launcher: ^6.3.1   # â† ADD THIS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
