name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # HTTP requests to your Flask backend
  http: ^1.6.0

  # Save CSV files to disk (Android/Desktop) + browser download support (Web)
  file_saver: ^0.2.14

  # Open links (export URL on web, mailto links, Buy Me a Coffee)
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
